import type { StationPublicInfo } from "@/types/telemetry";

export const DEFAULT_CENTRAL_LUZON_STATIONS: StationPublicInfo[] = [
  {
    stationPublicId: "Rjz2dbXW",
    stationName: "Popolon AWS - Palayan City",
    stationType: "WEATHERSTATION",
    address: "Manacnac, Palayan City, Nueva Ecija, Philippines",
    city: "Palayan City",
    state: "Nueva Ecija",
    country: "Philippines",
    isActive: true,
    location: [121.05767, 15.53683],
  },
  {
    stationPublicId: "3nzr8bGo",
    stationName: "Alasas AWS - San Fernando City",
    stationType: "WEATHERSTATION",
    address: "Alasas, San Fernando City, Pampanga, Philippines",
    city: "San Fernando City",
    state: "Pampanga",
    country: "Philippines",
    isActive: true,
    location: [120.6894, 15.0298],
  },
  {
    stationPublicId: "2Dpo5DAK",
    stationName: "1Bataan Command Center - Balanga City",
    stationType: "WEATHERSTATION",
    address: "Balanga City, Bataan, Philippines",
    city: "Balanga City",
    state: "Bataan",
    country: "Philippines",
    isActive: true,
    location: [120.5412, 14.6784],
  },
  {
    stationPublicId: "4VAl2p9k",
    stationName: "Sapang Buho AWS - Palayan City",
    stationType: "WEATHERSTATION",
    address: "Sapang Buho, Palayan City, Nueva Ecija, Philippines",
    city: "Palayan City",
    state: "Nueva Ecija",
    country: "Philippines",
    isActive: true,
    location: [121.0843, 15.5521],
  },
  {
    stationPublicId: "lMAZe9b3",
    stationName: "Abucay AWS - Bataan",
    stationType: "WEATHERSTATION",
    address: "Abucay, Bataan, Philippines",
    city: "Abucay",
    state: "Bataan",
    country: "Philippines",
    isActive: true,
    location: [120.5372, 14.7358],
  },
  {
    stationPublicId: "1Zb102pg",
    stationName: "San Jose City AWS - Nueva Ecija",
    stationType: "WEATHERSTATION",
    address: "San Jose City, Nueva Ecija, Philippines",
    city: "San Jose City",
    state: "Nueva Ecija",
    country: "Philippines",
    isActive: true,
    location: [120.9984, 15.7912],
  },
  {
    stationPublicId: "nDby4YpR",
    stationName: "General Natividad AWS - Nueva Ecija",
    stationType: "WEATHERSTATION",
    address: "General Natividad, Nueva Ecija, Philippines",
    city: "General Natividad",
    state: "Nueva Ecija",
    country: "Philippines",
    isActive: true,
    location: [121.0541, 15.6023],
  },
  {
    stationPublicId: "3nzr48bG",
    stationName: "Calumpit AWS - Bulacan",
    stationType: "WEATHERSTATION",
    address: "Macarthur Highway Gatbuca, Calumpit, Bulacan, Philippines",
    city: "Calumpit",
    state: "Bulacan",
    country: "Philippines",
    isActive: true,
    location: [120.7657, 14.9201],
  },
  {
    stationPublicId: "03pqkGAj",
    stationName: "Bongabon Water District AWS - Nueva Ecija",
    stationType: "WEATHERSTATION",
    address: "Bongabon, Nueva Ecija, Philippines",
    city: "Bongabon",
    state: "Nueva Ecija",
    country: "Philippines",
    isActive: true,
    location: [121.1458, 15.6312],
  },
  {
    stationPublicId: "95pM7BAV",
    stationName: "Doña Maria AWS - Balanga City",
    stationType: "WEATHERSTATION",
    address: "Doña Maria, Balanga City, Bataan, Philippines",
    city: "Balanga City",
    state: "Bataan",
    country: "Philippines",
    isActive: true,
    location: [120.5284, 14.6852],
  },
  {
    stationPublicId: "VEpdDpBK",
    stationName: "San Luis AWS - Aurora",
    stationType: "WEATHERSTATION",
    address: "San Luis, Aurora, Philippines",
    city: "San Luis",
    state: "Aurora",
    country: "Philippines",
    isActive: true,
    location: [121.5201, 15.7012],
  },
  {
    stationPublicId: "rqAkmpKG",
    stationName: "Barretto AWS - Olongapo City",
    stationType: "WEATHERSTATION",
    address: "Barretto, Olongapo City, Zambales, Philippines",
    city: "Olongapo City",
    state: "Zambales",
    country: "Philippines",
    isActive: true,
    location: [120.2641, 14.8542],
  },
  {
    stationPublicId: "wkAWLzlm",
    stationName: "Lazatin AWS - San Fernando City",
    stationType: "WEATHERSTATION",
    address: "Lazatin Boulevard, San Fernando City, Pampanga, Philippines",
    city: "San Fernando City",
    state: "Pampanga",
    country: "Philippines",
    isActive: true,
    location: [120.6812, 15.0341],
  },
  {
    stationPublicId: "QgbGldAY",
    stationName: "Pag-asa Bagac AWS - Bataan",
    stationType: "WEATHERSTATION",
    address: "Bagac, Bataan, Philippines",
    city: "Bagac",
    state: "Bataan",
    country: "Philippines",
    isActive: true,
    location: [120.4012, 14.6012],
  },
  {
    stationPublicId: "nDbyYbR1",
    stationName: "Sabang Morong AWS - Bataan",
    stationType: "WEATHERSTATION",
    address: "Sabang, Morong, Bataan, Philippines",
    city: "Morong",
    state: "Bataan",
    country: "Philippines",
    isActive: true,
    location: [120.2741, 14.6812],
  },
  {
    stationPublicId: "Bkpj1zRO",
    stationName: "Old Cabalan AWS - Olongapo City",
    stationType: "WEATHERSTATION",
    address: "Old Cabalan, Olongapo City, Zambales, Philippines",
    city: "Olongapo City",
    state: "Zambales",
    country: "Philippines",
    isActive: true,
    location: [120.3102, 14.8621],
  },
  {
    stationPublicId: "O3z0j5bG",
    stationName: "Calumpit WLMS - Bulacan",
    stationType: "WATERLEVEL",
    address: "Macarthur Highway Gatbuca, Calumpit, Bulacan, Philippines",
    city: "Calumpit",
    state: "Bulacan",
    country: "Philippines",
    isActive: true,
    location: [120.7657, 14.9201],
  },
];
